const Map<String, String> ar = {
  'Apptitle': 'تطبيق أعراسنا',
  'Login': 'تسجيل الدخول',
  'sign up': 'حساب جديد',
  'Home': 'الرئيسية',
  'Connection Success!': 'Connection Success!',
  'Connection Failed!': 'Connection Failed!',
  'Sing In': 'تسجيل الدخول',
  'Forgot Password': 'نسيت كلمة المرور',
  'Password': 'كلمة المرور',
  'Email': 'البريد الإلكتروني',
  'User': 'مستخدم',
  'Welcome Back': 'مرحبا بعودتك',
  'New Account': 'حساب جديد',
  'Re-Type Password': 'اعادة كلمة السر',
  'Sing in instead': 'أو قم بتسجيل الدخول',
  'Password Reset': 'تغيير كلمة المرور',
  'Close': 'إغلاق',
  'Profile': 'الملف الشخصي',
  'New Group': 'مجموعة جديدة',
  'New Chat': 'محادثة جديدة',
  'Calls': 'الاتصالات',
  'Settings': 'الاعدادات',
  'Support': 'الدعم الفني',
  'Sing Out': 'تسجيل الخروج',
  'My Location': 'موقعي',
  'Are you sure you want to exit?': 'هل تريد الخروج من التطبيق؟',
  'Yes': 'نعم',
  'No': 'لا',
  'wrong password': 'كلمة مرور غير صحيحة',
  'Logged in Successfully!': 'تم تسجيل الدخول بنجاح',
  'Sign out': 'تسجيل الخروج',
  'Signed out successfully!': 'تم تسجيل الخروج بنجاح',
  'By Categories': 'حسب الأصناف',
  'By Brands': 'حسب الشركات',
  'Products': 'المنتجات',
  'Product Details': 'معلومات المنتج',
  'Select Filter': 'طريقة عرض المنتجات',
  'All Products': 'جميع المنتجات',
  'Filterd by Category': 'عرض حسب صنف',
  'Filterd by Brand': 'عرض حسب شركة',
  'Add': 'اضافة',
  'Shop Now': 'المنتجات',
  'My Cart': 'السلة',
  'My Orders': 'طلبياتي',
  'Purchase History': 'مشترياتي',
  'Contact Us': 'كلمنا',
  'New Offers': ' العروض',
  'Language': 'اللغة',
  'Barcode': 'الباركود',
  'Category': 'التصنيف',
  'Box QTY': 'التعبئة',
  'Brand': 'الشركة',
  'Finicial Report': 'التقرير المالي',
  'Track Orders': 'متابعة الطلبيات',
  'Production Country': 'بلد المنشأ',
  'Min Order QTY': 'الحد الادنى للطلب',
  'Successfully Registered!': 'تم التسجيل بنجاح',
  'Please wait until Your Account is Activated!':
      'يرجى الانتظار لحين تفعيل الحساب',
  'Account Activation': 'تفعيل الحساب',
  'Short Username!': 'اسم مستخدم غير مقبول',
  'wrong Email!': 'ايميل غير صحيح',
  'Pasword must be at least 8 letters or numbers!':
      'كلمة السر مؤلفة من ثمان احرف أو ارقام على الأقل',
  'Paswords dont match!': 'كلمتا المرور غير متطابقتان',
  'Register': 'حساب جديد',
  'Please Contact Admin to  Activate your Account or check Internet Connection and Refresh by Scrolling Down':
      'يرجى التواصل مع الادارة لتفعيل حسابكم او التأكد من الاتصال بالانترنت و عمل تحديث للصفحة عن طريق السحب للاسفل',
  'Do You Really Wanna Sign out?': 'هل أنت متأكد من تسجيل الخروج؟',
  'Contact System Admin for Password Reset':
      'يرجى التواصل مع ادارة الشركة لاعادة ضبط كلمة المرور',
  'Please Login or Register New Account':
      'يرجى تسجيل الدخول او انشاء حساب جديد',
  'Remove': 'ازالة',
  'Cart is Empty': 'سلة المشتريات فارغة',
  'Check out': 'تثبيت الطلب',
  'Total': 'الاجمالي',
  'Value': 'القيمة',
  'Tax': 'الضريبة',
  'Order Total': 'اجمالي الطلبية',
  'Order Date': 'تاريخ الطلب',
  'Order Status': 'حالة الطلبية',
  'Order No': 'رقم الطلبية',
  'Accept Order Delivery': 'تأكيد استلام الطلبية',
  'Pending Admin Approval': 'بانتظار قسم المبيعات',
  'Pending Order Preperation': 'بانتظار قسم التحضير',
  'Pending Delivery Service': 'بانتظار توصيل الطلبية',
  'Pending Acceptance': 'بانتظار استلام الطلبية',
  'Order Details': 'تفاصيل الطلبية',
  'Delivered': 'مستلمة',
  'Deliverd Orders': 'الطلبيات المستلمة',
  'Opening Balance': 'رصيد قديم',
  'Discount': 'حسم مكتسب',
  'Payment': 'دفعة',
  'Purchases': 'مشتريات',
  'Returned Purchases': 'مرتجع مشتريات',
  'Other': 'اخرى',
  'Balance:': 'الرصيد'
};
