const Map<String, String> en = {
  'Apptitle': 'Wedding App',
  'Login': 'Login',
  'sign up': 'Sign Up',
  'Home': 'Home',
  'Connection Success!': 'Connection Success!',
  'Connection Failed!': 'Connection Failed!',
  'Sing In': 'Sing In',
  'Forgot Password': 'Forgot Password',
  'Password': 'Password',
  'Email': 'Email',
  'User': 'User',
  'Welcome Back': 'Welcome Back',
  'New Account': 'New Account',
  'Re-Type Password': 'Re-Type Password',
  'Sing in instead': 'Sing in instead',
  'Password Reset': 'Password Reset',
  'Close': 'Close',
  'Profile': 'Profile',
  'New Group': 'New Group',
  'New Chat': 'New Chat',
  'Calls': 'Calls',
  'Settings': 'Settings',
  'Support': 'Support',
  'Sing Out': 'Sing Out',
  'My Location': 'My Location',
  'Are you sure you want to exit?': 'Are you sure you want to exit?',
  'Yes': 'Yes',
  'No': 'No',
  'Logged in Successfully!': 'Logged in Successfully!',
  'Sign out': 'Sign out',
  'Signed out successfully!': 'Signed out successfully!'
};
